#!/bin/bash
# ==============================================================================
# Home Assistant Community Add-on: CloudflareDDNS
# ==============================================================================

bashio::log.info 'Starting the CloudflareDDNS...'

# Start the SSH daemon
exec /usr/sbin/ddns
