#!/bin/bash
# ==============================================================================
# Home Assistant Community Add-on: CloudflareDDNS
# ==============================================================================

echo -e 'Starting the CloudflareDDNS...'

# Start the SSH daemon
exec /usr/sbin/ddns
