#!/bin/bash
# ==============================================================================
# Home Assistant Community Add-on: CloudflareDDNS
# ==============================================================================

echo -e 'Starting the CloudflareDDNS...'

# Start the script
#exec /usr/sbin/ddns
exec /etc/cont-init.d/ddns
